{% set version = "1.0.0" %}

package:
  name: connect4
  version: {{ version }}

source:
  git_url: https://github.com/muff2n/connect4.git

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytorch
    - numpy
    - os
    - pandas
    - pickle
    - anytree
    - visdom

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    pytest tests

about:
  home: https://github.com/muff2n/connect4
  license: MIT
  summary: 'Someone should write a summary'
  description: 'Blank description'
